on: [push]

jobs:
  info:
    runs-on: self-hosted
    name: Plastic Config Test
    steps:
    - name: plastic config action step
      uses: TelltaleGames/plastic-config-action@main
      with:
        client_conf: ${{ secrets.PLASTIC_CLIENT_CONF }}

    - name: Plastic Repo List
      run: cm repo list